apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBaC98EyOiZueRxSlVms8icH+bbJzlLZvl2aBGmMPeEh+xsAuj6eR+5WjIwY125RS3XKKQjct48lj5wqq9kJAIleQsLpoL1ovjh5e2lN0o6D+D676k0j/EzArQKezttJXyNIOVsPR25eqcax7gY6QrfGX70qYgoYkELFn//M8tCrwzLMnaNILY+7eNFFLUgCwyzFlFC+KpAXOXDuDpkSz+kKzaZy1vqUTcx8QnG5VIfTr+N9HRTFEHDylFMqTc+8icqPfgj8+4tFMdLCDdW0r0VJzWeGcuL4VvTmCShYbtZjpj6jKjrX2OYNwOFL8M2jfw3EbAAS2Y6BBUZhXuairOgEkK1eMKm48sTCKpRTyQFwDZ8UyuEwT5wD4BmwTgKjXr+FQgOhA2x8FVdfwZpw1G2S2ZMjkH19UTFJmIS48ZdyWhtZkPOu4T7DIx+Xh/fcLXqVMv85VNHfqrGN/omvl+6854oqVparYZMJ1Vo6ZVU7Wlp/o4s7kcTF7OopeXqpRIcDD2gYnNCN/uZZmwmRCm/ZRp1YOAeD4PwaQNkzXH1HnEexSpBriA0GBeSQAoJT0PipIJn4isPEPAAjSi8yrtMb8B3c4+wI/i5SdW4zTHIt/tULlWT/vWmXLGOtQMhRK3Ib1h7htT94VOAfQ/CAWaHhDa9LV0a9ZUK5oyVHN1nUuqCEhK7Gp5jRxqdW3vR1DVMb7uaDT9CzHfb0NC6lR97C/GUX4n6HtjeybzpjfMtH8mppyeWT8D70eoadwPRNtXBhVCR6kSvNUKNad6NKRKnhHLCET+2FsZd31rgowQeDDiOGsRK5d0vk95MvDOi8jZZYicdn6Tq38cPhDLbCBwVxMGn3rCJHdLStWm80sYWnNWAc4Npjn8WAUMWdM50/Xi2Riwx0qqeo2AfuqDR3yRcG3lh+qdAwY2RUZq5O59d74OCbZQyUJ3a4ZbUuLkRdXL9QSmvMzoDzxYqJyL3Cc2ZpA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

