apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA8GRIJWBpBmZuI4vOeA4tCNBz/TkwODb74aG+8mVSwft5tpWu20dBvyNInK/rqTqVlq1i4uUCWjbW5NpxGOV3kee4dic01IjRKFqf96vUhLlFAgmLlS2nqFNnzt5I1xC3DrVc/eNEM7AoxULTwxLnI8n362axQulps/uK0dvtCSF61y0O6MG/Fk7/1psmJ6QGy20u6CBLs35sWvkUVInQPUMpTJ655HeJJ+7Jq95+hq+hvLF0r1HrBacuGcG9qwCSOe2R5G3GSZaOCGAjeryyWPY3S+lA8xOvsHPPUhI0BfDOvvYsehI9BmeI1+LLxQjf75mSgxSJoyDYUe0C6J/gdMNMwTKnkNMoaqDN1Kn11m8cXmXSFGE6toIm8so8tsgOhXEZhyHZi8EA+lRjXHHu5fz3RAciEv9bsk9id6e5rC9PR4QkvtiuNYwlaMOCCccJWmKAgj1dlFs/uUoWK6BbVAGTjMaENd6/Oc/Wm96ZKiPCMSvCQQKgVlq3h4n/HJWXrqZIJGJAnVO6FG7PeJmXio2sfE5E8N76CUB2ucnzDrZOGJku15zsOttbjGTo2YzzjjVq2iBFDPvja1DAgG8/N+MWFLD1Cch+oCqPBRhvyY2X2UgtImz9eH7pYO0fpj06LPs20oUIT+7ogvX9BAdqnChijdVDTgcninLPcEHKV54Su772pPbt5xOeC9VUrMaRzBr3bjopdU9yMCQPrlJ7MvLlN/FcpEpxGn4Jd7cgCmAuGaDQVl/aWpFNNwARvBqYxsKjPUpMRe9tMa/TpaYYYBZmfl/+QR6HP+T1PtkwFkNzyRDzSdpeicCuHAVQBscE9J4s8dlReiRxb5u0Jc/zQmHFrprHikC4hhB50e/M5c4M3v0y/0RrIAS/bIvZ2hqBh9GSjIOp+0qfFYrsP6mu4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

