apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAVCP+nmPj3tAVnmniOYQMNgx6V31XGElhFKBOER6nXYv0qromBI725qFfRnID43KCkPDey4m33w1Lz8MHDxlaeaoiEdr6mqSrjC0qbFRdaaCAFJXR1Nh7+DqpDpaLSUvg+FCx297eohdDyyxVwdJ5eIIkKJV3+oo98U4xz+GXvreYLR1c3ap6DD8vX6c2GXUgvpivLwPY2Q9hJ1abWRxNkErtiziia+UgkSRAw0sMZwBoYQ0lmOMfulef0ZujMoSPfCbiu7kKtqWr8T0z6rDlcsqABZCwb31UukKD41YncQD2874aAg1QkOdZKevreUA7yhl2tv5VuHe1yTVbs3RZLsc4j+rUtH64ExAbC3WD9+pvUfnCAi8xm+zudpbI8OnrITw2MP8OkI012un2jfv7Vr/R1bqoGTGLgfgtwTqA0dLs1dgG39ex6Y/R2FVcOzav7bLLKy1hIxPX4zsrEwEftLj+sYnbVtd+z9DVHuHDb5A5kU5JnP5FhvmNzs7Rtl3iZt9AOaAhcQR+i96aohVDSrL+EwuDG3SqUphZoYhJQvtdarquPw36xe6jJZ+gRs0Tw/uGXOX6KR+oBZYj8BU9tnpyv/lhxbO7GmQt2gPs2r8znzn6dbK4kPve2Is69PCupvPSCbJRoYYo3g1yKlKLolN3JvsF2TRmSNn/MNKo/sPxl7+nSKYxv9VuwuNahUWy8Am+0MELndoltIN4uOWwtCnz9u5HtRMbcVdw+tVRBOcUPt4bKIf72/rRR5pnOaVAi780Va4QfsTSkltvUsI+64HWSZn2NW/S5RJgiZGeMZo1KluKSph6J35heIGHq3t+tthslgFhR4DyUSznuimOd088znoLF+ua0MME4JHyFDNBv31d/xAjLbT4GKVCja7r9PhAap4wM5d2Agu1XHXon
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

