apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBRE0kSYinadQBFawICF2Ky60M5+vVI+cuvLK37O4ZYQO96PBSP/TniaoF6lzjreDweBlI68FHQXfr4dTmFAJsnKcUE1SCfDGcA4J78q8ZbOKGNG/qN7xBUvZZK9uxo8p6nE+kANOCZohTF7TobiaHeHp9wzo6VRntzxiDKAOp9iD4TGnuynPfT8l3Lwarwo9hl2WA3TsZVmoX5oBHFkJuqbFBesWte0rJgSppgYAfnPJMF+qH1fikrxFT5aSpnH15VSORoiWKhhRQVqaAU7yOQOPSZGiSr0zqDGXXoZtwoiGiKpEK9FV0q0o1iSdcstwHqesGJiBh1G/iWgku7Ro+1++ps0fr3dK2tCjOFYTFxBwMWcyDj0zHXrsvJi6F59QUFy6r27zurGGGJhbInx98ikheOEwg2GGsMw0ELyvNIjPjh1X7Wt64ubnunAbUHbVTgJN5oyNekrBt94t5ESfrR3H9yG5BGnypjgZE1WQoWI+FYy1XmpKVV3RR/ZZUm5ksly15yEsR72omL+s63ZNwZOweO8NZyWBlBu0qvVBOjfcuJDmBjcELtYSJbvMNRfud9p3jnuP23rCKdO3xL0ezvfWMW/KhmvTCp55Qwmdj0v0olbFzJ/8OsY8IMFAYruSydSpclvB8AMSlkX7Oytg1jCdXIyMadXYENWyX8PCTp9jL9XnuRKotnCkcetlVEGYikM2z8LNGPtSkcd+/Y7imvjUjLOvnaMRRYTl40PZ/1qNyq4ZZ/UmU5+S6eq96FsuwDQYM+6R0Geguf/kwgV6DWsli63w5CpU9E8KXFw1Wfxj5OZZYE/UxwqMcH6iVnCPJiG9gyHotZ4H9VV26F8FktYfLXAkgWM4RZtobja5AVoasZyM0m5TXCVsrWkVPwGyklQwyLtOW9FPgmhs+0MGuaP5Rz71hsQsUR9OL8j9R4+/sgmqKRo92u8nlSbAX1xnv+9Gjvk1yH6cHQ/FZ89ZTLNw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

