apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCsBNglSDcrIfczrUHhdx6B5mjnEjVv9+ZJ8SZq4JBD58AeJgs1BWULFzcbVBcCpDjCckod80XF/tsJRDy42JdnM1DedrYIPhY9TouJTLmsv1fh3YSmuWjwUwGuX/pY/4awqA7kVb78mMCyKCW+KBALZKDPONJTAYMUWEZk2t+Fem36QCOpdSTvBRBq7ZwwS+gArKOcXjOIOQCCDzj2Nny7exBKzq+u1ZbuWcC3Q5Pcj6fAzQV+CUT+zx0t+DDsBxrFPX0bLvzl/Ywkkk8gSvwUMKBArDjVU5sA6u1bNgsDORPA1kg9AKFR07jIyL0zPmbEtnec5+QlPaCw6IyhVCeGtDuz3n4BwbBlnfthV33joMViZ8tHzZfu5QffhYbuCPQ7v4l/g7RyDcabf+JjGVXe6Gz9S9ULCrgfHiYjC0WAvz/du3oRv+xXq24a26NnlZGb3vu/DEdP2jSlrjC2b+vyV37Qz/XD2hWxzJgCDQc75bC5tp1CyD1ahWTC467RoffEck8QCRWBIj3Uo8jHfO2cKS5ygaPfJ1bL8zFiyyPeN8/kkYKo5tr/qUGZGSuDfN5DdnM9pqCyTi6lDtO8iQ3Fxj1lzbMtSEnRt1KwMXminjU5UVdnPk4w71fMpSgyhsinokAuI8cUExxQcvrux/QS/IdcgD8I3nq3InA0OtRfa3tBEKrh0CaJuxMDjMQVCoLaI+08l0pwTqQb51hWXpYcZ4qsx1G5NzUKRd8KBTnQnkFSvX2gOvKMDBfc+/eNcEXUHPE95e2Q/3jLda5Ee/5J482llFALPgeDeMEnCdQqbZ0LRzHjvNe1k532Ne3Vf33XRWAMKoA1+j6xJ6BhLGfqPQ+Uj91/4aspoybvLlio3mXsNzchnqKzRNNIpPikFtpfSZ7YUKt4J1tAgxC93MQD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

