apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBLxjl8JKsn2OnutHBwqE1tKkiqA4ibrgVEPvk57DQ0a0S+epOzwexo7CSJgeWkDkWLxyHLhWsFgGthNqL7N5jMDrUDcR4tfPVq9xHmNp3YsJjXnOKPKmcsUKD6TXCQcu5/mMwbN8GQ8jJgsIy2v8crQArFFuICfqffHHeJOTQNrllicZMeOSns4KcJ8D98SrL1o44BSFtoXPzTzFPRdF82RdG9F+v0X6g4tzX8xHeRyPDZVKiKdi53AC+OYsnt6Q8RiAEBoOX0Z64a6iv6JmsxLV6sgYXi8AVLPp1Fq9+1l7TXQzYzK1pekIYBbqWTi00UWXqUW6Vp2t7GHZZq+oEd7brNfQxLzU2lKzRIKYx2dSRfbqCnoPqAaDRMxZR+c6elWke1SZBDy9JKWsCoVnUOSVgHxO/3lHfm3G9nL++ozZuuO20HM+CcDzzs1hSXe1p4AKz5GHX+6H03ykx3wknog1p2WZFo6fkXtJgge5aVpjWbz5xCebQdAtP2BVePd0XEqNNavzQjD+Pl/+1KSincwdxpvJ3EYL+bLWO9Ipn3g7warCim3Wznt7osT5KumYAntQSd7kQ9J3XbrYkyCv07MbMBsp6oNx5ae3MZ+CK9FgSb1jzWT1V7cTzU/3pYZ2B4ShQcaZHcQqIKgaNt31tuIAOe3O/Qw1Lecx9HkTmv8CmQSMJRnT0qjp3xpNZx/ZvQc6xov7S3eRtwcTDev9eawaugu/R0anEcGPLT38XBrf7DLv/+ekJXaCHdbdPsUMJs2t4SYP8TQUUMOqc6bQ5vKp85LO6ZKt1tsMSkGRf1bsKFMjyxA1OqPEzfeLXmZa5/sxjoHq7B7aOc59lZL+kkefEooJKfAhcghRvnMK+UoNPnJNe7rnu/IrO8Z9X2ZlltFtFbCvsSPfcym1T3q38g
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

