apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAxNMjITQq2pyi7g57o0WO9Wxu5W09gX1z7zbyuIc1Yvt8ukyXVM0k9ZL2w70v0QH/VaQR1puixTaYZH7xio7ifIRXXx5fQQLQnS6X2L9Ie8Kup0U2hGfmjCqb7DJlU2fgX2xt7q+d4A4SOXU76Db2kkPfOiCdgqqYHGlCB+3lTx04CCYFbDwAdTs9SsuII00KMEOiwE7AhEEgyYuNxEVSl4KCJMMFHfbMiIk83XIdL6YcyYeJYjxwiXjYgB5Zw6Z4AmHY6S1RRP2zSqA1M5o/a5Ds1lAGm0IQr+aYM4T+mHLALGBhMKdyLRVRaYUe34r9eKWK7Ia57moTG7TnNFoesvxWQvrLUocGKLLRLGtCdJbgQH5PZVDHAQniDzbJBGZRx0k0+L9qGjOOmB6rnj2fBzyxcVRsIS95GJaPkI2awhHHWdd08jEeQf7youUdko10q27MUzpmVLKBD/ndLk4RJQgOFQaX+oEsGIKOjLCgb/c9ygKD7p0JAAV91w0WoOxuNwjzz1mrAcZ+dSax4z2oR+64qAg6eizVpJ0XKU+GCPVA2AQYpLg9u1ZpY7JTvO2KeLvEWtVTBaD46R3swDialO3MrumekuyAgW12PjxyTPOKWjK3C+9TUi0O5KVDjSJgoNaZ0ZDsPv2gN8Be7LZK431bUtn/xpWbcaiOVgu+WkQhPDkxsEQjy56JkE4oLckzc3YUYE/doEkA9HO9BR7g9EDoQSyjS5u9+OSIlTMwPy0bxtZPrYvYx4krwsTY9z3Q3d/Yjg78gZasgY5pB5MlZ/pbY0kwF9FtYdaejV+NKCwFbELanEmka3PTDi42EVHp4W1+XR3dHD9Zq+Fkn/I4P5LHYL7cpsd9dNw0SmMdl4uN3VQUiJonVFDffCW4uVKRsYnNx/v4XQXf5z6LNau6KefgID7+tb/tlJXOhrbksb7jfv8haPM1MP/ni9zxkVc1IeV/NafQeWb3FPakv18RPPw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

