apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA0mDhUh6Dvg1oG+ifeJdpbYVFfKMw95Bbr7vDANIOjLcRG+anEEPbGgYTHDcibYgYF7qVfJbjp9dMJ4vrQxooZUrmjl59vgzikuUCk6PlSOIgtkkrNG8aR8xfE488r9r1uq+utPl6oRNLxWMKNAkgEk0kFvA4k2HpTokxB/drz88/4ts+IlZRmugyftmMXFClVo57Kg0OEKXY/tIfPj+t4UYBBnjhG+tGYvkrekvNlQIPYya2KPWJKmFHYzMCDRv1hyHM/WLnfP6sAbyXJAaxcUeciv7GGO4NbvveW3mHtkFJFEYH8JXnHxOkzJCPKQZjD+V6F8yVv6t2/BP2s8aQP4pCJc2Kx7wkJ2l/vF+S8CmytcpxGS34vOTmtZydL38g2C+Wr4y3hGYfeTG+iO5nn5laig5U/QdT1AQ7IgJG3iXGw87XfJbdVMFhOVN9pCgA325cbCWBPHtrZAgYMHT98RnT9WlYhhD8iKDB86iwdzhtLfjjsnIeLT6BALsJRe6o1lTdDklrFqK7Ok4fqT13U7r7VHQgob6qJJZG8LtgtNfF365M271XJP3Xlap0C5ii5Bx28njwmxx0P8zCSQCj+eqBJYiMa+exWC8ZI0e7IUqxf4OevK0XY2iftwri2+KvbZpg0Ji+2a8vPsGWsmItBh88eViwncR0VnZQYLVkbRPD/FXn8W+invbHluHYz9oUF8UsS0lEZYO3vy0eo0inYnyKZOUtvn5P7mjT40LfHLarvVIEZQQrb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

