apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBDwPql83ym2XDvXhvpw0HFpg8yG9GPNXApp69KZ44ZCWvAtehHygmDWkXQxHfqk9+WinO1Q9/ZOBgOK/hwFGxI7QEEqxkj8iO7yTR8EjTa7Jy8xZ2nLQP68Q1mCMCCTEzeBpUxFzzWNrasuorwMpcPs3w4/LgYcgoJK7gSuHgHihkh3xZ0kpsPLv3HMNGPtFRnih+pDR/POVc/W6sL3NTta4piDCLlQT0GKzOBI4V9u7/xL890bXun6oyElp0sS2KceOIDHv/0GZszAh9AegGxhpb+RumIl6wlx/cMcU3S82wCOsG8+Iss6nAcZk4wxc20iQNxhqQ5t+/8JDF2AD/1kDRvK5EsprmLh43UxRx6h5AoL029g/tbl6zgCuYPBaK/J7Z5qw32dkRQa+e3TAXA/9nE3iFiLPOUBsIWW65OZDUBAYDKW8SDgOsJUND5h+3glisYFTxLz/VvQK3E8THTo4LX+28tEUG85OnNOpAIWPxUJrD2PD7haJOFW/09jYpsajuMsm03SDcgK8vOkAjKreRgyCOWpVIV3KnumtiIpNQOUS4v5GmDczDbmgzMZzHptnoiydG2vfsEL1PlQZa9cOKIo6NQqT/oS8KG672T52tOHM6ieWTjdQAq/FXz5OMuTQKDi1hjTzZsKhboJP2oXHcy6O2uf9gA41tc0ODaSLN1vcaQGVOuu2Qyo/0qLfiqya15oEc2eiXO/pI8wsooM7+tq3020ORWpAs7styYwa3Y6Hkuj+wl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

