apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBk2ZqFJnhvkTyoXuvnQtorcofK3g4abKfFUfEAAP52raJYUfSn2nCytOBAfWiUllQptv092HlmlkCBkl9DqBDzdQIFe9FSHCP4SIOspL71FIz07RaWIoGQjg34vPiMCAyCJ21c7jAoOhycWaj2P125O9f26k9Ku0uZyQgeb7jNmjspd1gXieQkwyUcxFpGS3MoJ88j7VkE3leZkNU83zU/A+x01T+yDOPaYYH4o1UZ9R/OCgXFi3gokiK+4dYC86DV+Qe8OZ1rSMzQXE8xwuxXrb2sdALu3dG9o3+ZEivduGy3LOC9d3LP3L93KsAbI3lzgcdSVp5aOCxnT8lV+DiAcGjT0mjiKtelOLuOIgp6H6x7xLzzZrHYeAf+ajMKnBwtx0SQ1LNWIIMLT2rBNTAoJwe+uasK5qUQOgYY6PQ9DQHyIt0oQwoZ15zUUVBkwCFGxagAFbFJog2/bHXI8kKIIo4x6BB5yxGsYIhcss7XYpbaPU2G+/0qG1Mj5y5rrXisW2EvONazvSOTH5kPO8X++ut9v1M7uXhSOi1GvQ7qjTffoLKClkPIcvPs0eZ1aQKTI4+5IUPNDJKLr5tfDCIFjw65/Jn7jCy8g79jsr4wiEJAirxGeaJv/OieWsSstehpkBCPwSAHZfuhctQ/ajw/TsISyb6QKf1TfRIjPLO+lUbBvhqpRY/OD9yfFJ/GYqxKXKHApLGTgHGkQwP6xlBTM1zGvlMLL+HTqruYyMQSeI2e59bhqL3N
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

