apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAakFyDGK2bo4DRw3wgNydNmmxEEW0JzWpEujPT/CiBo0Thf3ufJOECn/c+ErwS0MfMSnvhpTDo8q8fnYSeS5x21q4oUgWzv5FJtqTZCwX/rm4MkYNM/Kk7/upIZDBVm2zL6GLoV2ue9RMJJw6YMnGwkpqFQh2sq8AgpCehgBI3UU34iV/QKP4j0qSHHT4Fp20KBp6uhU7I2mbGwH9QbUAdaggLcZr36MuuF0KdoF66WG0BzeMEF0Ff5X9iQjuWESkl5LA6dn2hu6gg+LjLYEm1rM0A+dzByQIJ5vmDec1EJEYcqhzMNFBDg9D5GJFNqYymY4aWrhikjfOxWBHRg8qrkhSjcswGmeyyV1gEXvkRCbLf81RNvYu5eeAdVbdO07LpU1EOEe5xqwDAWAMgBi4mKUlKsL/rDtU6Nm/OwQhcx+FwO9GYv4kt0RF67UivV1nZ7UB7Z8yOj6x0iS1/NuXz/sxbdZRRsQLbWyY23ZiQLibCTvyhePb4HRBIC4N1aoZAGVIexh5kO3mKR+J2oMVJ4EIyQ8bXHR4PaVGX0huGUpzuWRwsSUWUUab3REM7KofV6i864EMxtRfETVIVoq9g8yDffMOPvfZQY7C+HXziVEcc7X1MHGD/JFIHJZ0C8xxm9ewdMXZgjG7guL+xU9rpVEtr0YpYmEuy/LVtUfLNQyo7fxUPBLXaNPUzISMoQ80OPuW+4PWhdbn6le1G7BEYGSyPNm1jscnt8iGN39TX+BrfWk0DbDDm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

