apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAtfzmTLteANi+UKwpc+/vg4TaBwH1G28X1GFAOA0g9cWhG+Q8rOrR6Kihfh+W45vbF69vtJhpQwUuwINErDL1u3J4IXZKhzMqeFF1PfizEqRgou6scfjVBagcmJLEwlCa6T+G1kwbSbCT4ZW4tpOki0EOZIJPoq1No5SvrHm4czTvrM2fpQbOTGY6fuKSH1CMuN4kuplgxHuOn00leLrzQLSkaPTscPFP1TaGPELxi1qXgSIuVdkDNFMmzI1JXZgJz5s2z+Kj/+KKEhxXiGmYs1z0bhQPlpdWs7H7k0jpUzKOfOk/G9+Xpqw6SSEdoaHOjS8p+MNC02zBaEMCL2VI5dfQEBd+C4FUoqrQQMphUPZ2xD3N3p2BpoKkrIIIdMPURUcXOANLa6QawUt1Q++nkywYrr6e9raDpl4cgPjpYQ9H1IequCEnIbVi90HXoG3wQZp8zoU1EZtZDvkK4T9ZAkgUgDrFiGuVCsh8IfK6kYfmDxIXljh03CBUeMVDGEM5f7JvsO+4qzwnGRy3CPr8sNR1RpWDx016++qzawSAgL7ceKTRWkxsSmnzjlFBheK7rsurQPEFx92Gzk8MpufKvV7Y8LIUjYTrW/aaDy/FrwLuwZRKntHsntsdXQk3VEbWGKsPESdcokzt/ypmrOXrZChMls/doI4u5HpB10q5e6zKB/yX/ZKFGytt42kc93okusAf3tYENJQkwvzLElqzOjlt9P+LNlRYQZ/eXjhHEhcEUkm8gxazt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

