apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBQc7yihxpI+CYBCG2q8EmF0hGVp7v4KFWjAMHLqLs2GeAYtMJNqkqDjIhEp8iYgPGpQyl6Xic7QcGW1EEND9zC8PwX4NAhoPeZvEqWm92YM+X6+vM6QPiSHUJpgMSn5/6gAHjj+s2gNx68iigJpScXgoMSDjB+sK2eTcmutKogvju+wJK4pefONukRMbU4kWui6Ekk5gQJCnzF6lz4Bv4fPd6Wm8TXDkSeB3kaGTFLWKfd2YOQ6HK6GMgjCpW4mlNjRl3INEESgQZFjdC0FAfKUJLRlMs0RHWs6ds6jXofBviit5AzqkH00ZE3Isfj6pwpG6sZI51yv92nNfwYzSMZ0Z/R7pHN6UA3eGhTbhS7BAssASu6ij9vJhDgojZ3vyfdl6TGV3gSqA2z1p5bDNoPxl5rYhdnspTATsq3tZB/gqXa21cqq3F0r0+FL5+pFVRxFKDvtUxX7J1/5QIPwn6YYK73NZKk7L7FKuLMAqnUUqNofp0oPL4bPPPDEnBscOQf26rVe3BFloIGhYe0+xkGMY6ZMjSnGr0ed1jdcPMyuyZ4AI+OCH9ogAs5NqJOm7iAee4bawiGvqnX2NmE8UEJOE4go/uamhcON8gFKVrR6aSe3H1aM6KmtLF0jIInithJTMly2lHlyX67SWRZW1vjj7u8cF+IncXS+wkW4+yt8e3rCa1yRqgMAvs+rRPBG+xr0U+qe3J9bmyM9rbhMzLZbz/2pWRHOnjhfjeBXxcxw93OIOVZFeR+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

