apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAt7wYjzwEiRrzduZa4ZHAhpH1V/s2/PlWg4TmmSlR81eU2pu2V/XfGoX4Q+wGGPSjIm2ve72kiSMJV8JfY7WwgydbykX21oT+8+bYmMoIy/WplT55oS7ilWzuyyciGKSCO8dNUFo+eYsKxbS5TLw4+wXkMIayTICsF3eg0EkHVdVBg+hl5o2RMXq+vFdlnd/Y06ZEj5zenll6lf3Ek/JFgKeUkLzKA9ntAHmLCi7HrhCTFdfN4rdYUz+1dTaTxCqoFpOHQ542/m+8CMFGtnhChmoNYdlqcMHQVJ0Ah1SQ+somaXjM49ewKW5Gp/l+T3Xl617XInLA9pJV+NIrgpkKoXCyq4zlISKyJG7Il8Xy9787GjGeOSLdpmbcrB+5qIMOVgD6PVxoBMVYcmKnSNtmMWMBfT07lVhim+efWueD/xWYOqaqCpdB+U7FOBvpVqKT7jB9MdhQACVjZaSY6ItphJ2gvXrcvS2u0cc7md1S3AStypQb5HVwhDg3OQpdF/wcIgW0r9WCC0rZP7zBEeD7pUj0VfP3pV7L9tp7IYJHbR51G9kF5kCGDP9yC1kLVCPkXJ4eZ4+AWI0y/RKiwA1h6hZU9r3PE8DWOr+xxR0zXSOvlbBAdn7pvj5F2TMQCM5dkrLaCXfg/MrtBIUXn9pZJecI+htxlevMqHsY1ABVtqfnDxKPtTQU5oulPAeTITMHZVMqEFgdY6N70DS3WBbl8MF7VLy7iQLjMdF0muttHiwtX6eT8MIot
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

